[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt",
    "pip install gunicorn"
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
    "python manage.py migrate --noinput"
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 1 --timeout 600 --graceful-timeout 600 --keep-alive 600"
